from pathlib import Path

from items.item_id import ItemId


PROJECT_ROOT = Path(__file__).parent.parent
DARK_PIXEL_ICON_PATH = PROJECT_ROOT / "resources" / "spritepacks" / "DarkPixelUI" / "Icons"
DARK_PIXEL_UI_PATH = PROJECT_ROOT / "resources" / "spritepacks" / "DarkPixelUI" / "UI"

# This maps every available DarkPixelUI item-like image to its stable ItemId.
# Actual Item objs look to this for icon paths.
ICON_PATHS_BY_ITEM_ID: dict[ItemId, Path] = {
    ItemId.SCROLL: DARK_PIXEL_ICON_PATH / "01_Scroll.png",
    ItemId.RING: DARK_PIXEL_ICON_PATH / "02_Ring.png",
    ItemId.TORCH: DARK_PIXEL_ICON_PATH / "03_Torch.png",
    ItemId.HELM_04: DARK_PIXEL_ICON_PATH / "04_helm.png",
    ItemId.CHEST_05: DARK_PIXEL_ICON_PATH / "05_chest.png",
    ItemId.PANTS_06: DARK_PIXEL_ICON_PATH / "06_pants.png",
    ItemId.BOOTS_07: DARK_PIXEL_ICON_PATH / "07_boots.png",
    ItemId.GREEN_GEM: DARK_PIXEL_ICON_PATH / "08_gem_green.png",
    ItemId.BLUE_GEM: DARK_PIXEL_ICON_PATH / "09_gem_blue.png",
    ItemId.PURPLE_GEM: DARK_PIXEL_ICON_PATH / "10_gem_purple.png",
    ItemId.CROSS: DARK_PIXEL_ICON_PATH / "11_cross.png",
    ItemId.POTION_12: DARK_PIXEL_ICON_PATH / "12_potion.png",
    ItemId.NECK_13: DARK_PIXEL_ICON_PATH / "13_neck.png",
    ItemId.WATER: DARK_PIXEL_ICON_PATH / "14_Water.png",
    ItemId.SILVER_RING: DARK_PIXEL_ICON_PATH / "15_Silver_ring.png",
    ItemId.GOLD_RING: DARK_PIXEL_ICON_PATH / "16_Gold_ring.png",
    ItemId.BOTTLE: DARK_PIXEL_ICON_PATH / "17_Bottle.png",
    ItemId.BOTTLE_OF_POWER: DARK_PIXEL_ICON_PATH / "18_Bottle_of_power.png",
    ItemId.MANA_POTION_19: DARK_PIXEL_ICON_PATH / "19_Mana_potion.png",
    ItemId.POTION_20: DARK_PIXEL_ICON_PATH / "20_potion.png",
    ItemId.MANA_POTION_21: DARK_PIXEL_ICON_PATH / "21_Mana_potion.png",
    ItemId.POTION_22: DARK_PIXEL_ICON_PATH / "22_Potion.png",
    ItemId.MANA_POTION_23: DARK_PIXEL_ICON_PATH / "23_Mana_Potion.png",
    ItemId.MUSHROOM: DARK_PIXEL_ICON_PATH / "24_Mushroom.png",
    ItemId.MEAT: DARK_PIXEL_ICON_PATH / "25_Meat.png",
    ItemId.APPLE: DARK_PIXEL_ICON_PATH / "26_apple.png",
    ItemId.SKULL: DARK_PIXEL_ICON_PATH / "27_Skull.png",
    ItemId.BAG_28: DARK_PIXEL_ICON_PATH / "28_bag.png",
    ItemId.BAG_29: DARK_PIXEL_ICON_PATH / "29_bag.png",
    ItemId.MACE: DARK_PIXEL_ICON_PATH / "30_mace.png",
    ItemId.SPADE: DARK_PIXEL_ICON_PATH / "31_spade.png",
    ItemId.COIN: DARK_PIXEL_ICON_PATH / "32_coin.png",
    ItemId.STONE: DARK_PIXEL_ICON_PATH / "33_stone.png",
    ItemId.WOOD: DARK_PIXEL_ICON_PATH / "34_wood.png",
    ItemId.GLOVES_35: DARK_PIXEL_ICON_PATH / "35_glowes.png",
    ItemId.BOOK: DARK_PIXEL_ICON_PATH / "36_book.png",
    ItemId.LEAF: DARK_PIXEL_ICON_PATH / "37_leaf.png",
    ItemId.SWORD_38: DARK_PIXEL_ICON_PATH / "38_sword.png",
    ItemId.SWORD_39: DARK_PIXEL_ICON_PATH / "39_sword.png",
    ItemId.BOW: DARK_PIXEL_ICON_PATH / "40_bow.png",
    ItemId.ARROW: DARK_PIXEL_ICON_PATH / "41_arrow.png",
    ItemId.SHIELD_42: DARK_PIXEL_ICON_PATH / "42_shield.png",
    ItemId.SHIELD_43: DARK_PIXEL_ICON_PATH / "43_shield.png",
    ItemId.ROPE: DARK_PIXEL_ICON_PATH / "44_rope.png",
    ItemId.CRYSTAL: DARK_PIXEL_ICON_PATH / "45_crystal.png",
    ItemId.SKIN: DARK_PIXEL_ICON_PATH / "46_skin.png",
    ItemId.TREASURE: DARK_PIXEL_ICON_PATH / "47_treasure.png",
    ItemId.BOOTS_48: DARK_PIXEL_ICON_PATH / "48_boots.png",
    ItemId.PICK: DARK_PIXEL_ICON_PATH / "49_pick.png",
    ItemId.HELM_50: DARK_PIXEL_ICON_PATH / "50_helm.png",
    ItemId.PANTS_51: DARK_PIXEL_ICON_PATH / "51_pants.png",
    ItemId.CHEST_52: DARK_PIXEL_ICON_PATH / "52_chest.png",
    ItemId.AXE: DARK_PIXEL_ICON_PATH / "53_Axe.png",
    ItemId.SILVER_BAR: DARK_PIXEL_ICON_PATH / "54_silverbar.png",
    ItemId.FLOWER: DARK_PIXEL_ICON_PATH / "55_flower.png",
    ItemId.HELM_56: DARK_PIXEL_ICON_PATH / "56_helm.png",
    ItemId.CHEST_57: DARK_PIXEL_ICON_PATH / "57_chest.png",
    ItemId.BOOTS_58: DARK_PIXEL_ICON_PATH / "58_boots.png",
    ItemId.PANTS_59: DARK_PIXEL_ICON_PATH / "59_pants.png",
    ItemId.GLOVES_60: DARK_PIXEL_ICON_PATH / "60_glowes.png",
    ItemId.POTION_61: DARK_PIXEL_ICON_PATH / "61_potion.png",
    ItemId.POTION_62: DARK_PIXEL_ICON_PATH / "62_potion.png",
    ItemId.STAIRWAY: DARK_PIXEL_ICON_PATH / "63_stairway.png",
    ItemId.CANDLE: DARK_PIXEL_ICON_PATH / "64_candle.png",
    ItemId.RED_CRYSTALS: DARK_PIXEL_ICON_PATH / "65_redcrystals.png",
    ItemId.WAND: DARK_PIXEL_ICON_PATH / "66_wand.png",
    ItemId.BANDAGE: DARK_PIXEL_ICON_PATH / "67_bandage.png",
    ItemId.RELIC: DARK_PIXEL_ICON_PATH / "68_relic.png",
    ItemId.MAGIC_69: DARK_PIXEL_ICON_PATH / "69_magic.png",
    ItemId.MAGIC_70: DARK_PIXEL_ICON_PATH / "70_magic.png",
    ItemId.MAGIC_71: DARK_PIXEL_ICON_PATH / "71_magic.png",
    ItemId.MAGIC_72: DARK_PIXEL_ICON_PATH / "72_magic.png",
    ItemId.EQUIPMENT_BELT: DARK_PIXEL_UI_PATH / "Icon_Eq_Belt.png",
    ItemId.EQUIPMENT_BRACELET: DARK_PIXEL_UI_PATH / "Icon_Eq_Bracelet.png",
    ItemId.EQUIPMENT_CHEST: DARK_PIXEL_UI_PATH / "Icon_Eq_Chest.png",
    ItemId.EQUIPMENT_GLOVES: DARK_PIXEL_UI_PATH / "Icon_Eq_Glowes.png",
    ItemId.EQUIPMENT_HEAD: DARK_PIXEL_UI_PATH / "Icon_Eq_Head.png",
    ItemId.EQUIPMENT_JEWELRY: DARK_PIXEL_UI_PATH / "Icon_Eq_Jewelery.png",
    ItemId.EQUIPMENT_SHIELD: DARK_PIXEL_UI_PATH / "Icon_Eq_Shield.png",
    ItemId.EQUIPMENT_SHOULDER: DARK_PIXEL_UI_PATH / "Icon_Eq_Shoulder.png",
    ItemId.EQUIPMENT_TABARD: DARK_PIXEL_UI_PATH / "Icon_Eq_Tabard.png",
    ItemId.EQUIPMENT_TRINKET: DARK_PIXEL_UI_PATH / "Icon_Eq_Trinket.png",
    ItemId.EQUIPMENT_WEAPON: DARK_PIXEL_UI_PATH / "Icon_Eq_Weapon.png",
    ItemId.EQUIPMENT_ARROWS: DARK_PIXEL_UI_PATH / "Icon_Eq_arrows.png",
    ItemId.EQUIPMENT_BOOTS: DARK_PIXEL_UI_PATH / "Icon_Eq_boots.png",
    ItemId.EQUIPMENT_BOW: DARK_PIXEL_UI_PATH / "Icon_Eq_bow.png",
    ItemId.EQUIPMENT_NECK: DARK_PIXEL_UI_PATH / "Icon_Eq_neck.png",
    ItemId.EQUIPMENT_PANTS: DARK_PIXEL_UI_PATH / "Icon_Eq_pants.png",
    ItemId.EQUIPMENT_RING: DARK_PIXEL_UI_PATH / "Icon_Eq_ring.png",
}
