from enum import StrEnum


# These IDs identify Autumnwood item types independently of their display names or
# DarkPixelUI filenames. Numeric suffixes distinguish the source pack's separate
# visual variants when it does not give them more descriptive names. Equipment IDs
# cover the item-like art stored separately under DarkPixelUI/UI/Icon_Eq_*.png.

# NOTE
# When adding an ItemId, also add its DarkPixelUI icon path to item_icon_paths.py
# When changing and ItemID, change the corresponding value in item_icon_paths.py

class ItemId(StrEnum):
    SCROLL = "scroll"
    RING = "ring"
    TORCH = "torch"
    HELM_04 = "helm_04"
    CHEST_05 = "chest_05"
    PANTS_06 = "pants_06"
    BOOTS_07 = "boots_07"
    GREEN_GEM = "green_gem"
    BLUE_GEM = "blue_gem"
    PURPLE_GEM = "purple_gem"
    CROSS = "cross"
    POTION_12 = "potion_12"
    NECK_13 = "neck_13"
    WATER = "water"
    SILVER_RING = "silver_ring"
    GOLD_RING = "gold_ring"
    BOTTLE = "bottle"
    BOTTLE_OF_POWER = "bottle_of_power"
    MANA_POTION_19 = "mana_potion_19"
    POTION_20 = "potion_20"
    MANA_POTION_21 = "mana_potion_21"
    POTION_22 = "potion_22"
    MANA_POTION_23 = "mana_potion_23"
    MUSHROOM = "mushroom"
    MEAT = "meat"
    APPLE = "apple"
    SKULL = "skull"
    BAG_28 = "bag_28"
    BAG_29 = "bag_29"
    MACE = "mace"
    SPADE = "spade"
    COIN = "coin"
    STONE = "stone"
    WOOD = "wood"
    GLOVES_35 = "gloves_35"
    BOOK = "book"
    LEAF = "leaf"
    SWORD_38 = "sword_38"
    SWORD_39 = "sword_39"
    BOW = "bow"
    ARROW = "arrow"
    SHIELD_42 = "shield_42"
    SHIELD_43 = "shield_43"
    ROPE = "rope"
    CRYSTAL = "crystal"
    SKIN = "skin"
    TREASURE = "treasure"
    BOOTS_48 = "boots_48"
    PICK = "pick"
    HELM_50 = "helm_50"
    PANTS_51 = "pants_51"
    CHEST_52 = "chest_52"
    AXE = "axe"
    SILVER_BAR = "silver_bar"
    FLOWER = "flower"
    HELM_56 = "helm_56"
    CHEST_57 = "chest_57"
    BOOTS_58 = "boots_58"
    PANTS_59 = "pants_59"
    GLOVES_60 = "gloves_60"
    POTION_61 = "potion_61"
    POTION_62 = "potion_62"
    STAIRWAY = "stairway"
    CANDLE = "candle"
    RED_CRYSTALS = "red_crystals"
    WAND = "wand"
    BANDAGE = "bandage"
    RELIC = "relic"
    MAGIC_69 = "magic_69"
    MAGIC_70 = "magic_70"
    MAGIC_71 = "magic_71"
    MAGIC_72 = "magic_72"
    EQUIPMENT_BELT = "equipment_belt"
    EQUIPMENT_BRACELET = "equipment_bracelet"
    EQUIPMENT_CHEST = "equipment_chest"
    EQUIPMENT_GLOVES = "equipment_gloves"
    EQUIPMENT_HEAD = "equipment_head"
    EQUIPMENT_JEWELRY = "equipment_jewelry"
    EQUIPMENT_SHIELD = "equipment_shield"
    EQUIPMENT_SHOULDER = "equipment_shoulder"
    EQUIPMENT_TABARD = "equipment_tabard"
    EQUIPMENT_TRINKET = "equipment_trinket"
    EQUIPMENT_WEAPON = "equipment_weapon"
    EQUIPMENT_ARROWS = "equipment_arrows"
    EQUIPMENT_BOOTS = "equipment_boots"
    EQUIPMENT_BOW = "equipment_bow"
    EQUIPMENT_NECK = "equipment_neck"
    EQUIPMENT_PANTS = "equipment_pants"
    EQUIPMENT_RING = "equipment_ring"
